### ISSUE TITLE
[Feature Request] Implement a flag that lua scripts can access to confirm whether the game is Open Starbound

### ISSUE THREAD

**Issue by SnaveSutit** [OpenStarbound/OpenStarbound#150]
This would primarily be useful for mods that want to support the original game, while also taking advantage of Open Starbound's enhanced API if it's available.

**Comment by Lonaasan** [comment]
Heyo, there already exists a way:

return root.assetJson("/player.config:genericScriptContexts").OpenStarbound ~= nil;

i use it in my own mod, with other client checks too. here is the link:

[Prisma Compatibility Check](https://github.com/Lonaasan/Prisma/blob/main/Prisma/prisma/compatibility/check.lua)

**Comment by SnaveSutit** [comment]
Oh sick! Thank you
