### ISSUE TITLE
Ammo support for weapons?

### ISSUE THREAD

**Issue by Shadowblitz16** [OpenStarbound/OpenStarbound#153]
Can we get official support for ammo and ammo clips for weapons?

**Comment by Bottinator22** [comment]
This can already be done easily with standard mods and, as such, is not something for oSB to implement.

**Comment by Shadowblitz16** [comment]
@Bottinator22 @patmanf 
Show an example, or reopen.
People have made huge libraries just to support ammo in things like guns, and when I tested them they weren't very good.

And when I asked why they needed such a big library They said it's because starbound weapons can't detect when they are fired and consume an item from the inventory, so they needed to use other item types to get around it.

**Comment by DarianLStephens** [comment]
Sounds like what you need is the ability to detect when weapons are fired, and better manipulation of inventory items.
Some event that triggers when a weapon fires, and the ability to cancel it, would probably be fine.

**Comment by Shadowblitz16** [comment]
yep

**Comment by Bottinator22** [comment]
This is not something to be implemented on the engine level. If existing mods aren't good enough, you can make your own with Lua and JSON. This is not an engine limitation and not worth adding to oSB assets either. Changes to the actual design of the game are not within the scope of oSB; we are only improving the engine and making a few very minor other changes (even some of these are going a bit too far for an untoggleable feature)

**Comment by Bottinator22** [comment]
> Sounds like what you need is the ability to detect when weapons are fired, and better manipulation of inventory items. Some event that triggers when a weapon fires, and the ability to cancel it, would probably be fine.

Weapon firing is handled entirely in Lua. Source code is not responsible for weapon firing logic at all.
The `player` table already has everything you'd need to grab ammo from the inventory. Just give the ammo a tag, and use `player.consumeTaggedItem` (which isn't even from oSB) to consume it from the inventory.
