### ISSUE TITLE
Potential future of open starbound.

### ISSUE THREAD

**Issue by Shadowblitz16** [OpenStarbound/OpenStarbound#154]
Here are some suggestions on how you guys might move forward.

- Upload OpenStarbound as separate game on steam
- Require purchase of official starbound for assets (To keep tiy happy and keep him off the open starbound teams backs)
- Separate Engine into source repo and assets repo
- Work with modders to release high quality unofficial updates.
- Provide vanilla gamemode for mod compatability. (basically just starbound without unofficial updates.)

Updates would need to be kept at a high standard so we need someone who can make sure sounds, sprites, and mechanics fit well together.

**Comment by patmanf** [comment]
what
