### ISSUE TITLE
Chinese Text wrap bug

### ISSUE THREAD

**Issue by DAIL7069** [OpenStarbound/OpenStarbound#2]
It seems that there is a problem with Chinese text rendering, and there is a problem with text wrapping.this is my test. /spawnitem avianhistory7-codex![2023-10-19_215334](https://github.com/OpenStarbound/OpenStarbound/assets/135861944/ba06b754-8f7e-4150-bfb3-527d11df7f5f)
[ZNTEST.zip](https://github.com/OpenStarbound/OpenStarbound/files/13043608/ZNTEST.zip)

**Comment by Novaenia** [comment]
fixed in https://github.com/OpenStarbound/OpenStarbound/commit/b2a5bd00fb1d7531591a1074a8571b5ae566f0dd
