### ISSUE TITLE
StarTestUniverse.cpp compile & game_test.exe failure  

### ISSUE THREAD

**Issue by dirbasti** [OpenStarbound/OpenStarbound#6]
Hi,

StarTestUniverse.cpp is missing a parameter in line 45 and 56: m_client->update(); . I can compile game_tests.exe after inserting float dt = GlobalTimestep * GlobalTimescale; a few lines before and rewriting them to m_client->update(dt).

However, two tests fail then:
[----------] 2 tests from SpawnTest
[ RUN      ] SpawnTest.RandomCelestialWorld
unknown file: error: C++ exception with description "(PlayerException) No matching filename for uuid '8952a9c7ecba7bc139ff6619706b6969'" thrown in the test body.
[  FAILED  ] SpawnTest.RandomCelestialWorld (174 ms)
[ RUN      ] SpawnTest.RandomInstanceWorld
unknown file: error: C++ exception with description "(PlayerException) No matching filename for uuid '1972f5be6814062dda65d507ac2d2a5b'" thrown in the test body.
[  FAILED  ] SpawnTest.RandomInstanceWorld (142 ms)
[----------] 2 tests from SpawnTest (317 ms total)

I am new to programming and cannot fix that myself. Could you please advice?

**Comment by Novaenia** [comment]
should be fixed now
