### ISSUE TITLE
How to not load Steam mods?

### ISSUE THREAD

**Issue by xiaojiafei520** [OpenStarbound/OpenStarbound#98]
I'm creating a Starbound modpack, and all the mods are placed in the mods folder within the game directory.
However, when I try to use OpenStarbound to make the modpack, it automatically loads the mods I've already subscribed to on the Steam Workshop.

**Comment by patmanf** [comment]
add `"includeUGC" : false` to your sbinit.config

**Comment by xiaojiafei520** [comment]
ok,it's work! TY! :333
